name: Deploy to GitHub Pages

on:
  push:
    branches:
      - cross_platform

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      - name: Build Web
        # The --dart-define line below replaces your .env file
        run: |
          flutter build web --release \
          --dart-define=WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} \
          --base-href "/Sky_Scanner/"

      - name: Upload Artifact 📦
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4